SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_ACCELERATION = 120
PLAYER_DECELERATION = 40
MANUAL_DECELERATION_MULTIPLIER = 8

SHOT_RADIUS = 5

POWERUPS_RADIUS = 40
SHIELD_TRIGGER_COMBO = 4
SHIELD_TIMER = 5

LASER_TRIGGER_COMBO = 8
LASER_TIMER = 10

EXPLOSION_TIMER = 1
EXPLOSION_SPEED = 50
